#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run test

# Update submodules recursively and remotely to the latest commit on main branch
git submodule update --recursive --remote

# Add changes submodules changes to the staging area before commiting
git add academy-presentation-tooling
